# Site settings
title: DatumEdge
email: js102@zepler.net
baseurl: ""
url: "https://www.datumedge.co.uk"
disqus_shortname: datumedge
twitter_username: hertzsprrrung
github_username:  hertzsprung
stackoverflow_userid: 150884
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

paginate: 5
relative_permalinks: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
markdown: kramdown
permalink: pretty
