# Site settings
title: DatumEdge
email: js102@zepler.net
baseurl: ""
url: "http://hertzsprung.github.io"
twitter_username: hertzsprrrung
github_username:  hertzsprung
flickr_username: hzsp
linkedin_userid: james-shaw-ba759a65
researchgate_userid: James_Shaw14
googlescholar_userid: HKgUofEAAAAJ
orcid: 0000-0002-0928-3604
stackoverflow_userid: 150884
stackexchange_userid: 50566

# Build settings
markdown: kramdown
permalink: pretty
